### ISSUE TITLE
site createtv does not work properly

### ISSUE THREAD

**Issue by snabben** [drftpd-ng/drftpd#129] opened 2020-04-23 13:47 UTC
When using site createtv you get: [2] 500 Not a valid section, aborting

**DrFTPd**
 - OS: Debian
 - Java version 14
 - drftpd version 4

**FTP Client:**
 - OS: Windows 10
 - FTP software: FTPRush

**Additional context**
There is no error in master.log

**Comment by snabben** [comment] 2020-04-24 09:54
tvmaze.conf
race.section.1=tv
race.section.2=tv-720p
race.section.3=tv-1080p
search.release=true
search.hd.section.1=tv-720p
search.hd.section.2=tv-1080p
search.sd.section.1=tv
tvmazebar.enabled=true
tvmazebar.directory=true

sections.conf
I just add the tv sections, numbers are in order =)

16.path=/tv
16.name=tv
18.path=/tv-720p
18.name=tv-720p
22.path=/tv-1080p
22.name=tv-1080p
Site sections:
(11:52:41) [2] 200- tv           /tv
(11:52:41) [2] 200- tv-1080p /tv-1080p
(11:52:41) [2] 200- tv-720p /tv-720p

**Comment by mvangoor** [comment] 2020-04-24 19:29
So this issue was related to site reload not working as intended fixed by k2r with b3a83102d487bf5ae7add44cc57fc34ea450c9e2
And the error message is misleading, fixed by c297f5e2e0132c4b49884e81d92a2f16fb9e645a

**Closed** 2020-04-24 19:29 UTC
Labels: investigate
